#!/bin/bash

TARGET="target/avr-atmega2560/release"
INPUT="avr2560.elf"
OUTPUT="avr2560.hex"  

cargo build --release
avr-objcopy -O ihex $TARGET/$INPUT $OUTPUT
sudo avrdude -v -p atmega2560 -c wiring -P /dev/ttyUSB0 -b 115200 -F -D -U flash:w:$OUTPUT    